### ISSUE TITLE
MQTT data reecive

### ISSUE THREAD

**Issue by atikeryazilim** [fischertechnik/txt_training_factory#1]
@AlexanderSteiger Hello
We purchased Factory Simulation 9V. We updated all TXT controller for version 4.5.1.
How we can receive data by Mqtt and fishertechnik-cloud? We have the fishertechnik-cloud account.
Could you help us about this issue ?

**Comment by AlexanderSteiger** [comment]
Unfortunately, it is not possible to use this programs with the factory simulation 9V because some required components are missing. You need 
https://www.fischertechnik.de/en/products/simulating/training-models/551584-sim-training-factory-industry-4-0-9v-simulation

**Comment by atikeryazilim** [comment]
Hi @AlexanderSteiger 
First of all, thank you for your return.I did not  understand a thing  as mentioned below that i updated all txt controller firmware for mqtt broker(version 4.5.1).So, they has got mqtt.Why do we need to have the product which you noticed in link below.Even if txt controller version  is 4.5.1,does not all system support MQTT? I only would like to receive obtained sensors’ datas i have has.
Best regard.
