### ISSUE TITLE
Exchange Cloud

### ISSUE THREAD

**Issue by stefan-balke** [fischertechnik/txt_training_factory#2]
Hi there,

thanks for making this all open source.
For research purposes, I'd like to send the MQTT messages to another gateway and then, eventually, to another storage infrastructure.

Some questions related to this:
- How often do you send messages to the cloud? What is your "sampling" rate?
  I guess this is the main thread here and it sleeps for 50ms? https://github.com/fischertechnik/txt_training_factory/blob/master/TxtFactoryMain/src/main.cpp#L907
  Which would mean a sampling rate of 50Hz.
- What are the sampling rates of the individual sensors. Is there an overview available?
- Is there any aggregation of the senor data already on the device or is the raw sensor data the payload of the MQTT message?
- Where is the data which goes on the MQTT message assembled? In each module?

Thanks in advance!
Stefan

**Comment by stefan-balke** [comment]
Alright, related to the MQTT payload, this is described here:
https://fischertechnik.github.io/txt_training_factory_doc/html/md_MqttInterface.html

**Comment by AlexanderSteiger** [comment]
> * How often do you send messages to the cloud? What is your "sampling" rate?
>   I guess this is the main thread here and it sleeps for 50ms? https://github.com/fischertechnik/txt_training_factory/blob/master/TxtFactoryMain/src/main.cpp#L907
> * What are the sampling rates of the individual sensors. Is there an overview available?

The default sample rate is 60 seconds for BME680 and the brightness sensor. The camera is per default deactivated. There exist a MQTT config message to change the rate and to start the camera. If the connection to the fischertechnik cloud is made, the sample rate is then 3 seconds for the sensors and 2 fps for the camera.

> * Is there any aggregation of the senor data already on the device or is the raw sensor data the payload of the MQTT message?

There is no aggregation of the sensor data on the device, but in the database of fischertechnik cloud 1 sensor value per minute is stored in the user account database.

> * Where is the data which goes on the MQTT message assembled? In each module?

Each station / MQTT client publish messages to the local MQTT broker, the MQTT bridge on the main TXT controller forward all the messages to the remote MQTT broker

Kind Regards
Alexander Steiger

**Comment by stefan-balke** [comment]
Hey Alexander,

thanks for the response.

Where do I find the exchange between local broker and remote broker in the code?

**Comment by stefan-balke** [comment]
Okay, these docs help me: https://github.com/fischertechnik/txt_training_factory/blob/master/TxtSmartFactoryLib/doc/MqttInterface.md#other-clouds
