### ISSUE TITLE
TxtParkPos project:  libTxtBME680BSECLib is missing

### ISSUE THREAD

**Issue by CvanLeeuwenFt** [fischertechnik/txt_training_factory#7]
I tried to compile the factory under Eclipse under Windows 10 but the TxtBME680BSECLib project or in the deps the library is missing.

**Comment by CvanLeeuwenFt** [comment]
I looks like that the source and header files are part of the TxtSmartFactoryLib project now.
The referens to the TxtBME680BSECLib and the library need to be remove from several project properties.
Some examples:

![image](https://user-images.githubusercontent.com/13519935/72206798-5ee29a80-3492-11ea-9ea7-a443a652c9c2.png)

![image](https://user-images.githubusercontent.com/13519935/72206842-bbde5080-3492-11ea-9fc1-eedc0cd2f94d.png)

**Comment by CvanLeeuwenFt** [comment]
There are may more errors in the library paths:
The release parts are sometimes referring to _Debug libraries.

**Comment by RAMI40** [comment]
Hi Carel, 

regarding the missing libraries - do we need to contact the manufacturer or the developer, where can we obtain the missing libraries.  

Regarding the library paths the information provided is very limited especially when it comes to Windows. I have been experimenting in Eclipse with library paths.  

I am following your tutorial which you posted and it is extremely helpful. 

Best Regards

**Comment by RAMI40** [comment]
I am not sure but under Configurations shouldnt we select - [All Configurations] - this is what i selected when i was importing the four projects in Eclipse but I can be wrong also. 

You have marked "Every Conf", "Every" under Configuration field what are implying with that

**Comment by RAMI40** [comment]
https://github.com/fischertechnik/txt_demo_c_download 

You referred me to this Link in another post. 

Just check out the Snapshots on the Link above - under Configuration  it is "All Configurations"

But there also the Libraries paths are missing i am referring the snapshot below.

![Eclipse_Snapshot_5](https://user-images.githubusercontent.com/41453219/72211547-75f2ae00-34cd-11ea-8aaf-bc9a81147111.png)

**Comment by CvanLeeuwenFt** [comment]
Their are no llibraries missing but the project settings are not right. They are not update after changng the project structure.
All configurations means a general setting for all the configurations, if you select one configuration then you are able to configure only that configuration.
But this is basic knowledge for development environments like Eclipse, MS-Visual Studio an others.
For this reason, it is advisable to start with more simple projects.

**Comment by AlexanderSteiger** [comment]
eclipse project settings fixed
