### ISSUE TITLE
SLD program broken in 0.8.1 release

### ISSUE THREAD

**Issue by JamesT42** [fischertechnik/txt_training_factory#9]
Hi!
I recently updated the Lernfabrik from 0.7.0 to 0.8.1. But the SLD does not work with the new program. It is independent of the color.
Please see this video:
https://www.youtube.com/watch?v=CQjII7JunOc

It still works with the old code, so I do not think it is a problem with my Lernfabrik.

Any ideas?

**Comment by AlexanderSteiger** [comment]
Please change the calibration file Calib.SLD.json in /opt/knobloch/Data/

The old version contains no "count", the new version needs the 3 values for count

example file:
```
{
 "SLD" : 
 {
  "colorsens" : 
  {
   "th1" : 887,
   "th2" : 1404
  },
  "count" : 
  {
   "blue" : 26,
   "red" : 15,
   "white" : 5
  }
 }
}
```

**Comment by JamesT42** [comment]
The example is missing a { in the first line. But then the solution works. Also the documentation needs to be updated, otherwise everyone will have the same problem.

**Comment by AlexanderSteiger** [comment]
Thanks!
